name: Create Release
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  create-a-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
             
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME: date +"%Y-%m-%d"
        with:
          tag_name: $TIME-snap
          release_name: $TIME-snap
          body: |
            # Automatic create relase at $TIME
            SHA: ` $GITHUB_SHA `
          draft: false
          prerelease: false

