name: Create Release
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  create-a-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
             

      - name: Create Release
        run: |
          echo "$(date +"%Y-%m-%d")-snap" >> ${GITHUB_ENV}

        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${GITHUB_ENV}
          release_name: ${GITHUB_ENV}
          body: |
            # Automatic create relase at ${GITHUB_ENV}
          draft: false
          prerelease: false