name: Update list
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-list-and-push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AdAway
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt'
          file-name: 'AdAway.txt'
          location: './adlists'

      - name: MalwareDomainList.com Hosts List
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://www.malwaredomainlist.com/hostslist/hosts.txt'
          file-name: 'MalwareDomainList.txt'
          location: './adlists'

      - name: AdGuard DNS filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
          file-name: 'AdGuard-DNS-filter.txt'
          location: './adlists'

      - name: EasyList
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist-downloads.adblockplus.org/easylist.txt'
          file-name: 'EasyList.txt'
          location: './adlists'

      - name: EasyList China
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
          file-name: 'EasyList-China.txt'
          location: './adlists'

      - name: EasyPrivacy
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist.to/easylist/easyprivacy.txt'
          file-name: 'EasyPrivacy.txt'
          location: './adlists'

      - name: EasyList Cookie List
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist-downloads.adblockplus.org/easylist-cookie.txt'
          file-name: 'EasyList-Cookie-List.txt'
          location: './adlists'

      - name: Fanboy's Social Blocking List
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist.to/easylist/fanboy-social.txt'
          file-name: 'Fanboy-Social-Blocking-List.txt'
          location: './adlists'

      - name: Fanboy's Annoyance List
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://easylist.to/easylist/fanboy-annoyance.txt'
          file-name: 'Fanboy-Annoyance-List.txt'
          location: './adlists'

      - name: anti-AD
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/easylist.txt'
          file-name: 'anti-AD.txt'
          location: './adlists'

      - name: anti-AD for dnsmasq
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/anti-ad-for-dnsmasq.conf'
          file-name: 'anti-AD-for-dnsmasq.conf'
          location: './adlists'

      - name: anti-AD for Pi-Hole
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/domains.txt'
          file-name: 'anti-AD-for-Pi-Hole.txt'
          location: './adlists'

      - name: anti-AD for Surge
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/surge.txt'
          file-name: 'anti-AD-for-Surge.txt'
          location: './adlists'

      - name: anti-AD for SmartDNS
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/anti-ad-for-smartdns.conf'
          file-name: 'anti-AD-for-SmartDNS.conf'
          location: './adlists'


      - name: Commit Updates
        run: |
          if [ -z "$(git status --porcelain)" ]; then
              exit 0
            else
              git add .
              git config --local user.email "bmyjacks@outlook.com"
              git config --local user.name "bmyjacks"
              git commit -m "Updated lists at $(date +"%Y-%m-%d")" -a
            fi

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
