name: Update filters
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-list-and-push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Specific area
      - name: AdGuard Russian Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt'
          file-name: 'AdGuard-Russian-Filter.txt'
          location: './specific-area'

      - name: AdGuard English Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt'
          file-name: 'AdGuard-English-Filter.txt'
          location: './specific-area'

      - name: AdGuard Japanese Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_7_Japanese/filter.txt'
          file-name: 'AdGuard-Japanese-Filter.txt'
          location: './specific-area'

      - name: AdGuard French Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_16_French/filter.txt'
          file-name: 'AdGuard-French-Filter.txt'
          location: './specific-area'

      - name: AdGuard Chinese Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt'
          file-name: 'AdGuard-Chinese-Filter.txt'
          location: './specific-area'

      ## Anti-AD
      - name: anti-ad-for-dnsmasq.conf
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/anti-ad-for-dnsmasq.conf'
          file-name: 'anti-ad-for-dnsmasq.conf'
          location: './specific-area/Anti-AD'

      - name: anti-ad-easylist.txt
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/easylist.txt'
          file-name: 'anti-ad-easylist.txt'
          location: './specific-area/Anti-AD'

      - name: anti-ad-adguard.txt
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/adguard.txt'
          file-name: 'anti-ad-adguard.txt'
          location: './specific-area/Anti-AD'

      - name: anti-ad-domains.txt
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/domains.txt'
          file-name: 'anti-ad-domains.txt'
          location: './specific-area/Anti-AD'

      - name: anti-ad-surge.txt
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/surge.txt'
          file-name: 'anti-ad-surge.txt'
          location: './specific-area/Anti-AD'

      - name: anti-ad-surge2.txt
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/surge2.txt'
          file-name: 'anti-ad-surge2.txt'
          location: './specific-area/Anti-AD'

      - name: anti-ad-clash.yaml
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/clash.yaml'
          file-name: 'anti-ad-clash.yaml'
          location: './specific-area/Anti-AD'

      - name: anti-ad-smartdns.conf
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://anti-ad.net/anti-ad-for-smartdns.conf'
          file-name: 'anti-ad-smartdns.conf'
          location: './specific-area/Anti-AD'


      - name: Commit Updates
        run: |
          if [ -z "$(git status --porcelain)" ]; then
              exit 0
            else
              git add .
              git config --local user.email "bmyjacks@outlook.com"
              git config --local user.name "bmyjacks"
              git commit -m "Update filters at $(date)" -a
            fi

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
