name: Update filters
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  update-list-and-push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Specific area
      - name: AdGuard Russian Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt'
          file-name: 'AdGuard-Russian-Filter.txt'
          location: './specific-area'

      - name: AdGuard English Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt'
          file-name: 'AdGuard-English-Filter.txt'
          location: './specific-area'

      - name: AdGuard Japanese Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_7_Japanese/filter.txt'
          file-name: 'AdGuard-Japanese-Filter.txt'
          location: './specific-area'

      - name: AdGuard French Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_16_French/filter.txt'
          file-name: 'AdGuard-French-Filter.txt'
          location: './specific-area'

      - name: AdGuard Chinese Filter
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt'
          file-name: 'AdGuard-Chinese-Filter.txt'
          location: './specific-area'


      - name: Commit Updates
        run: |
          if [ -z "$(git status --porcelain)" ]; then
              exit 0
            else
              git add .
              git config --local user.email "bmyjacks@outlook.com"
              git config --local user.name "bmyjacks"
              git commit -m "Update filters at $(date)" -a
            fi

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
